name: Deploy project to our server
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.softvencefsd.xyz
          username: griti@griti.softvencefsd.xyz
          password: "aJ9SjJxrcUVQC3nm3T0g"
          # server: 146.63.205.92.host.secureserver.net
          # username: dolceresetapp@backend.dolceresetapp.online
          # password: "5OipIT=Iq5oWVg0q"
